# Generated by Django 4.2 on 2024-08-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('market_cap_currency', models.CharField(max_length=10)),
                ('market_cap_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('purchased_amount', models.IntegerField(default=0)),
                ('purchased_status', models.CharField(max_length=255)),
                ('request_data', models.DateField()),
                ('company_code', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('five_days', models.FloatField()),
                ('one_month', models.FloatField()),
                ('three_months', models.FloatField()),
                ('year_to_date', models.FloatField()),
                ('one_year', models.FloatField()),
                ('competitors', models.ManyToManyField(to='stocks.competitor')),
            ],
        ),
    ]
